---
title: "FlowJo from TLS data"
author: "Sidney van der Zande"
date: "`09-07-2024`"
output: html_document
---

# Information

This script is used to analyse the FlowJo data generated in the TLS experiments, which are a part of investigating tertiary lymphoid structure (TLS) responses to immune checkpoint blockade (ICB) in the PDTF platform. It takes as input the Excel files exported from each individual FlowJo experiment.

```{r Load libraries}
#Load libraries
library(readxl)
library(openxlsx)
library(stringr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(data.table)
library(ggsignif)
```

# Generate data
```{r Read in data}
#read in data and add experiment number
flow_file_TLS016 <- read_excel("~/Documents/Experiments/TLS/TLS016_LU088_LU091_22042024_SZ_NS/TLS016.xls")
flow_file_TLS016$experiment <- "TLS016"
flow_file_TLS015 <- read_excel("~/Documents/Experiments/TLS/TLS015_LU066_LU083_15042024_SZ_NS/TLS015.xls")
flow_file_TLS015$experiment <- "TLS015"
flow_file_TLS014 <- read_excel("~/Documents/Experiments/TLS/TLS014_LU023_LU052_10042024_SZ_NS/TLS014.xls")
flow_file_TLS014$experiment <- "TLS014"
flow_file_TLS013 <- read_excel("~/Documents/Experiments/TLS/TLS013_LU023_LU035_28032024_SZ_NS/TLS013.xls")
flow_file_TLS013$experiment <- "TLS013"
flow_file_TLS012 <- read_excel("~/Documents/Experiments/TLS/TLS012_LU066_LU083_22032024_SZ_NS_PK_GC_RW/TLS012.xls")
flow_file_TLS012$experiment <- "TLS012"
flow_file_TLS011 <- read_excel("~/Documents/Experiments/TLS/TLS011_21032024_SZ_NS_PK_GC_RW/TLS011.xls")
flow_file_TLS011$experiment <- "TLS011"
flow_file_TLS010 <- read_excel("~/Documents/Experiments/TLS/TLS010 SZ NS 14032024/TLS010_AF.xls")
flow_file_TLS010$experiment <- "TLS010"
flow_file_TLS009 <- read_excel("~/Documents/Experiments/TLS/TLS009_LU086_SZ_NS_29022024/TLS009.xls")
flow_file_TLS009$experiment <- "TLS009"

#combine data from all experiments
flow_file <- rbind(flow_file_TLS009, flow_file_TLS010, flow_file_TLS011, flow_file_TLS012,
                   flow_file_TLS013, flow_file_TLS014, flow_file_TLS015, flow_file_TLS016)
colnames(flow_file) <- c("Name", "Statistic", "Cells","Experiment")
```

```{r Isolate fragments}
#grab individual fragments, distinguished as #1, #2 etc.
fragments <- flow_file[grepl("#|fragment",flow_file$Name),]

#remove entries that do not contain full fragment or B cell data
fragments <- fragments[!grepl("CD3|T cell|Myeloid|CD20+|Cell Cycle|unknown",fragments$Name,ignore.case = T),]

#remove PBMC data
fragments <- fragments[!grepl("PBMC",fragments$Name,ignore.case = T),]

#remove single stains
fragments <- fragments[grepl("LU",fragments$Name,ignore.case = T),]

```

```{r Calculate the MFI of several markers and couple them to samples}
#The median of a marker is always below the population it refers to. Use this:
MFI_expression_file <- data.frame()

for(i in 1:nrow(flow_file)){
  if(grepl("Median", flow_file$Name[[i]])){ #if the line contains MFI information
    
    #grab median expression value: the name of the marker is in front of the =, the MFI after it
    MFI_row_stat <- strsplit(flow_file$Name[[i]],"=")
    
    #grab marker name
    MFI_row_marker <- MFI_row_stat[[1]][1]
    MFI_row_marker <- gsub("Median : Comp-|-A| " , "", MFI_row_marker)
    
    #grab MFI
    MFI_row_stat <- MFI_row_stat[[1]][2]
    MFI_row_stat <- gsub(" ", "", MFI_row_stat) #remove spaces
    
    #find the row it corresponds to
    for(j in 1:i){
      #look in all rows above the entry
      if(grepl("LU", flow_file$Name[[i-j]])){
        row <- flow_file$Name[[i-j]] #if there is a tumour sample found, couple the value to this sample and exit the loop
        break
      } else if (grepl("stim|unstim", flow_file$Name[[i-j]])) {
        row <- NA #if there is a PBMC sample found, do not enter a sample and exit the loop
        break
      } else {
        next #if no sample is found on this row, go to the row above it
      }
    } 
    
    #quick check: if no B cells are there, the MFI will be n/a, so leave this entry out
    if(is.na(MFI_row_stat)){
      next
    }
    
    if(is.na(row)){
      next #if the row is NA, this was a PBMC sample, so do not couple it
    }
    
    #make the data entry
    row <- gsub("/B cells", "", row)
    row_full <- data.frame(Name = row, marker = MFI_row_marker, MFI = MFI_row_stat)
    
    #append to data.frame
    MFI_expression_file <- rbind(MFI_expression_file, row_full)
  }
}


#remove NA values
MFI_expression_file <- MFI_expression_file[!is.na(MFI_expression_file$Name),]

#Couple the fluorochromes to an actual marker
MFI_expression_file$marker[MFI_expression_file$marker == "BB515"] <- "HLA-DR"
MFI_expression_file$marker[MFI_expression_file$marker == "BUV563"] <- "CD86"
MFI_expression_file$marker[MFI_expression_file$marker == "PE"] <- "CD80"

#reshaping to wide
MFI_expression_file_wide <- spread(MFI_expression_file, key = marker, value = MFI)
MFI_expression_file_wide[,-1] <- sapply(MFI_expression_file_wide[,-1],as.numeric)

#add to table
fragments <- left_join(fragments, MFI_expression_file_wide, by = "Name")
```

```{r Add B cell information}
#add B cell information present in second row
fragments_noB <- fragments[!grepl("B cell", fragments$Name),] #make a data frame of sample names
B_cell_info <- data.frame()

for (i in 1:nrow(fragments_noB)){
  name <- fragments_noB$Name[[i]]
  name_B_cell <- paste0(name, "/B cells") #grab flowjo path of B cell gate
  B_cell <- fragments[fragments$Name %in% name_B_cell,] #select the gate entries containing B cell data
  
  colnames(B_cell)[colnames((B_cell)) == "Cells"] <- "B_cells"
  colnames(B_cell)[colnames((B_cell)) == "Statistic"] <- "B_cell_percentage"
  
  #couple back to original data frame
  B_cell$Name <- gsub("/B cells", "", B_cell$Name)
  
  B_cell$CD80 <- NULL
  B_cell$CD86 <- NULL
  B_cell$`HLA-DR` <- NULL
  
  B_cell_info <- rbind(B_cell_info,B_cell)
  
}

#add B cell information to data frame
B_cell_info$Experiment <- NULL
B_cell_info[,-1] <- sapply(B_cell_info[,-1],as.numeric)
fragments_noB <- left_join(fragments_noB, B_cell_info, by = "Name")

#note: NA values for B cell counts/percentages is because I did not gate fragments split up over multiple clusters (like 1 and 1_2)

#rename columns for clarity
colnames(fragments_noB) <- c("Name","percent_of_CD45","cells", "experiment", "CD80_B_cell_MFI","CD86_B_cell_MFI","HLA-DR_B_cell_MFI", "B_cell_percentage",
                             "B_cells")
fragments_noB$percent_of_CD45 <- as.numeric(fragments_noB$percent_of_CD45)
```

```{r Add T cell information}
#add T cell information
T_cell_data <- flow_file[grepl("CD3\\+ T", flow_file$Name),] #grab all entries gated from the CD3+ T cell population
T_cell_data <- T_cell_data[!grepl("PBMC",T_cell_data$Name),] #exclude PBMC stains
test <- strsplit(T_cell_data$Name, "/") #split each gate up into individual segments

T_cell_info <- data.frame()

for (i in seq_along(test)){ #for each gate
  result <- test[[i]][grepl("\\+",test[[i]])] #specific population on this line of the file
  
  sample <- test[[i]][grepl("\\.fcs",test[[i]])] #sample in which the population was found
  
  if(grepl("unstim|stim",sample)){
    if(!grepl("LU",sample)){ #if it is a PBMC sample, skip
      next
    }
  }
  
  #give the T cell population a name:
  if(any(grepl("CD4",result))){
    T_cell_name <- paste0("CD4+ ", tail(result,1)) #if the gate concerns CD4+ T cells, the gate is named as 'CD4+ CD...+'
  } else if(any(grepl("CD8",result))){
    T_cell_name <- paste0("CD8+ ", tail(result,1))  #if the gate concerns CD8+ T cells, the gate is named as 'CD8+ CD...+'
  } else if(any(grepl("DN", test[[i]]))){ #check DN and DP populations in original list as they do not contain a + sign
    T_cell_name <- "CD3+ DN"
  } else if(any(grepl("DP", test[[i]]))){
    T_cell_name <- "CD3+ DP"
  } else {
    T_cell_name <- "CD3+"
  }
  
  #grab the number of cells and percentages for that population
  T_cell_count <- T_cell_data[i,"Cells"] #since the list and the dataframe are in the same order, we can just work with the list index for the data frame
  T_cell_count <- as.numeric(T_cell_count)
  T_cell_percentage <- T_cell_data[i,"Statistic"]
  T_cell_percentage <- as.numeric(T_cell_percentage)
  
  #add the real sample name (without all the T cell gating)
  sample_name <- T_cell_data[i,"Name"]
  sample_name <- gsub("/CD3\\+ T cells", ":",sample_name)
  sample_name <- strsplit(sample_name, ":")
  sample_name <- sample_name[[1]][1]
  
  #make and export the data
  T_cell_row <- data.frame(Name = sample_name, population = T_cell_name, percentage = T_cell_percentage, count = T_cell_count)
  
  T_cell_info <- rbind(T_cell_info, T_cell_row)
}

#filter out some artefacts
T_cell_info$population[T_cell_info$population == "CD4+ CD4+ T"] <- "CD4+"
T_cell_info$population[T_cell_info$population == "CD4+ CD4+"] <- "CD4+"
T_cell_info$population[T_cell_info$population == "CD8+ CD8+ T"] <- "CD8+"
T_cell_info$population[T_cell_info$population == "CD8+ CD8+"] <- "CD8+"


#convert to wide, separately for percentage and count
T_cell_percentages <- T_cell_info[,c("Name","population","percentage")]
T_cell_counts <- T_cell_info[,c("Name","population","count")]

T_cell_percentages <- spread(T_cell_percentages, key = population, value = percentage)
colnames(T_cell_percentages)[-1] <- paste0(colnames(T_cell_percentages)[-1], "_percentage")
T_cell_counts <- spread(T_cell_counts, key = population, value = count)
colnames(T_cell_counts)[-1] <- paste0(colnames(T_cell_counts)[-1], "_counts")
```

```{r Add information on tumour, condition, etc.}
#get the condition and tumour out by strsplit
fragments_noB_condition <- strsplit(fragments_noB$Name, "/")
fragments_noB_condition <- sapply(fragments_noB_condition,"[[",1)

#few gsub commands to get all condition naming the same for all samples
fragments_noB_condition <- gsub("_"," ",fragments_noB_condition,ignore.case = T)
fragments_noB_condition <- gsub("fragment","",fragments_noB_condition,ignore.case = T)
fragments_noB_condition <- gsub("pool","",fragments_noB_condition,ignore.case = T)
fragments_noB_condition <- gsub("\\.fcs", "", fragments_noB_condition)
fragments_noB_condition <- gsub("Tumor|Tumor ", "", fragments_noB_condition)
fragments_noB_condition <- gsub("aPD1\\+ahrIFNyR1|aIFNgR1\\+aPD1|aIFNgR \\+ aPD1|aIFNgR1 \\+ aPD1|aPD1\\+aIFNR1|aIFNgR1\\+aPD1|aIFNgR \\+ aPD1|ahrIFNyR1\\+aPD1|aPD1\\+aIFNR|aPD1\\+aIFNR|hrIFNyR1 \\+ aPD1|IFNgR1 \\+ aPD1", "aIFNyR1+aPD1", fragments_noB_condition)
fragments_noB_condition <- gsub("rhIFNg|IFNg", "hrIFNy", fragments_noB_condition)
fragments_noB_condition <- gsub("rhIFNg|IFNg", "hrIFNy", fragments_noB_condition)
fragments_noB_condition <- gsub("hrhrIFNy", "hrIFNy", fragments_noB_condition)
fragments_noB_condition <- gsub("hrhrIFNy", "hrIFNy", fragments_noB_condition) #artefact caused by the line above
fragments_noB_condition <- gsub("Unstim", "unstim", fragments_noB_condition)
fragments_noB_condition <- gsub(" 1| 2| 3| 4| 5| 6| 7| 8| 9| 10| 11", "", fragments_noB_condition)
fragments_noB_condition <- gsub("LU86", "LU086", fragments_noB_condition)
fragments_noB_condition <- gsub("unstim ", "unstim", fragments_noB_condition)

#Split the tumour, number and condition
test <- strsplit(fragments_noB_condition, " ")

#grab tumour numbers out
tumours <- unlist(lapply(test, grep, pattern="LU", value=TRUE))

#grab the condition (which is always the last entry in the list)
conditions <- sapply(test,tail,1)

conditions[conditions == "aPD1+ahrIFNyR1"] <- "aIFNyR1+aPD1" #renames any missed condition


#add the information back to the sample list
fragments_noB$tumour <- tumours
fragments_noB$condition <- conditions

#add fragment information
names <- strsplit(fragments_noB$Name, "#|fragment_") #split at the # sign indicating a fragment
names <- sapply(names,"[[",2) #grab the fragment number
names <- gsub("\\?","",names) #rename fragments named as #9? to #9 (for example)
names <- gsub("_1.fcs|.fcs","",names) #remove the file extension

fragments_noB$fragment <- names
```

```{r Merge duplicated fragment entries}
#remove fragments that are split up into two (marked by a _2); their concatenated sample should be present already in the file
duplicate <- fragments_noB[grepl("_2", fragments_noB$fragment),] #grab all fragments with the _2 extension

concat_final <- data.frame()
delete <- data.frame()

for(i in 1:nrow(duplicate)){ #for each of the duplicated entries
  #grab all entries: the concatenated entry but also the individual entries
  row <- duplicate[i,]
  fragment <- gsub("_2|_3", "", row$fragment) #remove the extension from their name
  
  #for entries concerning conditional replicates (aPD1 vs aPD1 2), the other fragment will also be identified, so exclude the other condition:
  if(grepl("2.fcs", row$Name)){
    row$condition <- paste0(row$condition, " 2")
  }
  
  #grab all entries connected to the duplicated fragment: same experiment, tumour, condition and fragment number
  corresponding <- fragments_noB[fragments_noB$experiment %in% row$experiment & fragments_noB$tumour %in% row$tumour & fragments_noB$condition %in% row$condition & fragments_noB$fragment %in% fragment,]
  
  if(any(grepl("2.fcs", corresponding$Name)) & !grepl("2.fcs", row$Name)){
    corresponding <- corresponding[!grepl("2.fcs", corresponding$Name),] #if a fragment was grabbed from a conditional replicate where the original duplicate fragment was
    #not from a replicate, discard this entry (correct for aPD1 vs aPD1 2)
  }
  
  #this is to identify a fragment ending on _3:
  corresponding3 <- fragments_noB[fragments_noB$experiment %in% row$experiment & fragments_noB$tumour %in% row$tumour & fragments_noB$condition %in% row$condition & fragments_noB$fragment %in% paste0(fragment,"_3"),]
  
  full_dup <- rbind(row,corresponding) #add all identified fragments together
  
  if(nrow(corresponding3) != 0){ #in case a third (_3) fragment is identified
    full_dup <- rbind(full_dup,corresponding3)
  }
  
  #for entries concerning LU086, this will also identify fragments coming from the other replicate (LU086_1 and LU086_2). Select for the correct tumour:
  if(grepl("LU086", row$Name) & row$experiment == "TLS011"){
    if(grepl("LU086_1", row$Name)){
      full_dup <- full_dup[grepl("LU086_1", full_dup$Name),] #exclude LU086_2 entries
    } else if(grepl("LU086_2", row$Name)){
      full_dup <- full_dup[grepl("LU086_2", full_dup$Name),] #exclude LU086_1 entries
    }
  }
  
 
  #the trick is this: the concatenated entry containing both clusters will not have a "percent of CD45" statistic
  #as they are not gated from anything
  #Select the concatenated entry using this, calculate the percentage of CD45 stat by adding up the individual percentages
  concat <- full_dup[is.na(full_dup$percent_of_CD45),] #the concatenated entry
  individual <- full_dup[!is.na(full_dup$percent_of_CD45),] #the individual entries
  
  concat$percent_of_CD45 <- sum(individual$percent_of_CD45) #calculate the new % of CD45+ by adding up the individua fragments
  
  #save the concatenated entry to later add this back into the full data frame
  concat_final <- rbind(concat_final, concat)
  
  #the individual entries and the unedited concatenated entry can now be removed from the full data frame:
  delete <- rbind(delete, full_dup)
  }

#now delete the individual and unfinished concat fragments
fragments_noB <- fragments_noB[!(fragments_noB$Name %in% delete$Name),]

#and add back the finished concat fragments
fragments_noB <- rbind(fragments_noB, concat_final)
```

```{r Thresholding and TLS classification}
#add information on whether the fragment has passed the 100 cell threshold
fragments_noB$cell_threshold_100 <- ifelse(fragments_noB$cells >= 100, "YES", "NO")

#add information on whether the fragment is a TLS, normal or tumour bed
fragments_noB$segment <- NA

for (i in 1:nrow(fragments_noB)){
  if (fragments_noB$B_cell_percentage[[i]] < 10 | is.na(fragments_noB$B_cell_percentage[[i]])){
    fragments_noB$segment[[i]] <- "tumour_bed"
  } else if (fragments_noB$B_cell_percentage[[i]] >= 10 & fragments_noB$B_cell_percentage[[i]] < 25){
    fragments_noB$segment[[i]] <- "intermediate"
  } else if (fragments_noB$B_cell_percentage[[i]] >= 25){
    fragments_noB$segment[[i]] <- "TLS"
  }
}
```

```{r Data corrections}
#separate samples with an extremely high IFN concentration (only occurred in experiments TLS009 and TLS010)
fragments_noB$condition[fragments_noB$condition == "hrIFNy" & fragments_noB$experiment %in% c("TLS009", "TLS010")] <- "hrIFNy_high"

#correction: for LU091, the last two columns (fragments #10 and #11) are actually LU088
fragments_noB$fragment[fragments_noB$tumour == "LU091" & fragments_noB$fragment == "10"] <- "12"
fragments_noB$fragment[fragments_noB$tumour == "LU091" & fragments_noB$fragment == "11"] <- "13"

fragments_noB$tumour[fragments_noB$tumour == "LU091" & fragments_noB$fragment %in% c("12","13")] <- "LU088"

#another correction: in TLS013, no hrIFNy was added for LU035, making this an unstim
fragments_noB$fragment[fragments_noB$tumour == "LU035" & fragments_noB$condition == "hrIFNy" & fragments_noB$experiment == "TLS013"] <- as.numeric(fragments_noB$fragment[fragments_noB$tumour == "LU035" & fragments_noB$condition == "hrIFNy" & fragments_noB$experiment == "TLS013"]) + 11
fragments_noB$condition[fragments_noB$tumour == "LU035" & fragments_noB$condition == "hrIFNy" & fragments_noB$experiment == "TLS013"] <- "unstim"

#last correction: sometimes, we fill multiple rows with the same condition, 
#making it such that there will be multiple fragments named 1 (and 2, and so on) in the same tumour in the same condition.
#continue with the numbering, so fragment aPD1 2 #1 becomes aPD1 #12 etc..
fragments_backup <- fragments_noB
fragments_noB$fragment[grepl("hrIFNy 2|aPD1 2|aPD1\\+aIFNgR1 2|aPD1\\+aIFNR 2",fragments_noB$Name)] <- as.numeric(fragments_noB$fragment[grepl("hrIFNy 2|aPD1 2|aPD1\\+aIFNgR1 2|aPD1\\+aIFNR 2",fragments_noB$Name)]) + 11

#correction for an incorrectly named condition
fragments_noB$condition[fragments_noB$condition == "aPD1+ahrIFNyR1"] <- "aIFNyR1+aPD1"
```

```{r Add T cell information}
#add T cell information
T_cell_data_full <- full_join(T_cell_percentages,T_cell_counts, by = "Name")
fragments_noB <- left_join(fragments_noB, T_cell_data_full, by = "Name")
```

```{r Save the result}
#save the table
write.csv(fragments_noB, "~/Documents/Analyses/TLS/fragment_table.csv")
```

# Plotting and data export

```{r Read in data}
#read in table
fragments_noB <- read.csv("~/Documents/Analyses/TLS/fragment_table.csv", check.names = F) #same table as generated above
fragments_noB[,1] <- NULL
```

```{r Filtering}
#continue without RN samples
fragments_small <- fragments_noB[!(fragments_noB$condition %in% c("RN440-15","RN440-16")),]
#also remove fragments that did not pass the 100 cell threshold
fragments_small <- fragments_small[fragments_small$cell_threshold_100 == "YES",]
```

```{r Count amount of TLS in each tumour}
#plot TLS number
counts <- fragments_small %>%
  group_by(tumour, cell_threshold_100, condition, segment) %>% #group by tumour, condition and segment type
  filter(cell_threshold_100 == "YES") %>% #remove fragments that did not pass the 100 cell threshold
  dplyr::count()

counts$cell_threshold_100 <- NULL

#split up per tumours
LU023 <- counts[counts$tumour == "LU023",]
LU035 <- counts[counts$tumour == "LU035",]
LU052 <- counts[counts$tumour == "LU052",]
LU066 <- counts[counts$tumour == "LU066",]
LU080 <- counts[counts$tumour == "LU080",]
LU083 <- counts[counts$tumour == "LU083",]
LU086 <- counts[counts$tumour == "LU086",]
LU088 <- counts[counts$tumour == "LU088",]
LU091 <- counts[counts$tumour == "LU091",]

#combine in a list
count_list <- list(LU023, LU035, LU052, LU066, LU080, LU083, LU086, LU088, LU091)
names(count_list) <- c("LU023", "LU035", "LU052", "LU066", "LU080", "LU083", "LU086", "LU088", "LU091")

#for each tumour: convert the data of fragments per niche to a wide format
for (i in seq_along(count_list)){
  count_list[[i]]$tumour <- NULL
  count_list[[i]] <- as.data.frame(count_list[[i]])
  colnames(count_list[[i]]) <- c("condition", "segment", "value")
  wide <- reshape(count_list[[i]], idvar = "condition", timevar = "segment", direction = "wide")
  wide[is.na(wide)] <- 0 #if a niche was not found, set it to zero
  
  #correct for missing conditions; set these to zero
  conditions <- c("unstim", "aPD1", "aIFNyR1+aPD1", "hrIFNy")
  missing <- conditions[!(conditions %in% wide$condition)]
  if(length(missing) > 0){
    missing_add <- c(missing,0,0,0) #assuming no more than 1 condition missing
    suppressWarnings(wide <- rbind(wide, missing_add))
  }

  #correct for missing segments; set these to zero
  if(any(grepl("TLS",colnames(wide)))){
    colnames(wide)[[which(grepl("TLS",colnames(wide)))]] <- "TLS"
  } else{
    TLS <- c(0,0,0,0)
    wide$TLS <- TLS
  }
  
  if(any(grepl("intermediate",colnames(wide)))){
    colnames(wide)[[which(grepl("intermediate",colnames(wide)))]] <- "intermediate"
  } else{
    intermediate <- c(0,0,0,0)
    wide$intermediate <- intermediate
  }
  
  if(any(grepl("tumour_bed",colnames(wide)))){
    colnames(wide)[[which(grepl("tumour_bed",colnames(wide)))]] <- "tumour_bed"
  } else{
    tumour_bed <- c(0,0,0,0)
    wide$tumour_bed <- tumour_bed
  }

  #reorder
  wide <- wide[order(match(wide$condition, conditions)),]
  segments <- c("TLS","intermediate","tumour_bed")
  wide <- wide[,order(match(colnames(wide), segments))]
  
  count_list[[i]] <- wide
}

#save the result for each tumour
write.csv(count_list[["LU023"]], "~/Documents/Analyses/TLS/LU023_TLS_counts.csv")
write.csv(count_list[["LU035"]], "~/Documents/Analyses/TLS/LU035_TLS_counts.csv")
write.csv(count_list[["LU052"]], "~/Documents/Analyses/TLS/LU052_TLS_counts.csv")
write.csv(count_list[["LU066"]], "~/Documents/Analyses/TLS/LU066_TLS_counts.csv")
write.csv(count_list[["LU080"]], "~/Documents/Analyses/TLS/LU080_TLS_counts.csv")
write.csv(count_list[["LU083"]], "~/Documents/Analyses/TLS/LU083_TLS_counts.csv")
write.csv(count_list[["LU086"]], "~/Documents/Analyses/TLS/LU086_TLS_counts.csv")
write.csv(count_list[["LU088"]], "~/Documents/Analyses/TLS/LU088_TLS_counts.csv")
write.csv(count_list[["LU091"]], "~/Documents/Analyses/TLS/LU091_TLS_counts.csv")
```

```{r Export T/B cell numbers per fragment type/condition to csv files}
#Collect data for prism
fragments_small$segment <- factor(fragments_small$segment, levels = c("TLS", "intermediate","tumour_bed"))
fragments_summarised <- split(fragments_small, fragments_small$segment) #split data per niche type (TLS, intermediate, tumour bed)

fragments_summarised_final <- list()
condition <- c("unstim", "aPD1", "aIFNyR1+aPD1", "hrIFNy", "hrIFNy_high")

for(i in seq_along(fragments_summarised)){ #for each niche
  fragments_summarized_data <- fragments_summarised[[i]] %>%
    group_by(tumour, condition) %>%
    summarise(count = n(), across(where(is.numeric), \(x) mean(x, na.rm = TRUE))) #take colMeans in all numeric columns in each group (take means of each column across fragments in each tumour and condition)
  
  fragments_summarized_data[fragments_summarized_data == "NaN"] <- NA
  
  #reorder based on condition
  fragments_summarized_data <- fragments_summarized_data[order(fragments_summarized_data$tumour, match(fragments_summarized_data$condition, condition)),]
  fragments_summarized_data$condition <- factor(fragments_summarized_data$condition, levels = condition)
  
  fragments_summarized_data <- fragments_summarized_data[fragments_summarized_data$condition != "hrIFNy_high",] #remove hrIFNy_high samples
   
  #add to list
  fragments_summarised_final[[length(fragments_summarised_final) + 1]] <- fragments_summarized_data
  names(fragments_summarised_final)[[length(fragments_summarised_final)]] <- names(fragments_summarised)[[i]]
}


#mass export to prism
for(i in seq_along(fragments_summarised_final)){ #for each niche
  data <- as.data.frame(fragments_summarised_final[[i]])
  for (j in 1:ncol(fragments_summarised_final[[i]])){ #for each column (averaged gate)
    if(is.numeric(data[,j])){ #if the column contains statistics
      colname <- colnames(data)[[j]]
      long <- data[,c("tumour","condition", colname)]
      colnames(long) <- c("tumour", "condition", "value")
      wide <- reshape(long, idvar = "tumour", timevar = "condition", direction = "wide") #convert to wide
      
      #rename columns
      colnames(wide)[colnames(wide) == "value.unstim"] <- "unstim"
      colnames(wide)[colnames(wide) == "value.aPD1"] <- "aPD1"
      colnames(wide)[colnames(wide) == "value.aIFNyR1+aPD1"] <- "aIFNyR1+aPD1"
      colnames(wide)[colnames(wide) == "value.hrIFNy"] <- "hrIFNy"
      
      #save as csv
      file_location <- paste0("~/Documents/Analyses/TLS/mass_data_export/",names(fragments_summarised_final)[[i]],"_",colname,".csv")
      
      write.csv(wide,file_location)
    }
  }
}
```

```{r Plot cell proportions}
#cell proportions test: can we plot different CD4+ and CD8+ populations?
cd8 <- fragments_small[,c("Name","experiment","tumour", "condition", "fragment","segment","CD8+_percentage","CD8+ CD25+_percentage","CD8+ CD39+_percentage","CD8+ CD103+_percentage","CD8+ CD137+_percentage","CD8+ OX40+_percentage","CD8+ PD-1+_percentage","CD8+ IL7R+_percentage")]
summary_cd8 <- cd8 %>%
  group_by(condition, segment) %>%
  summarize(across(6:12, \(x) mean(x, na.rm = TRUE))) #take the mean percentage of each population across all fragments, separated by condition and segment type (TLS, intermediate, tumour bed)

colnames(summary_cd8) <- gsub("_percentage", "", colnames(summary_cd8)) #remove the 'percentage' from the column names

summary_cd8_long <- melt(summary_cd8) #convert to long format

summary_cd8_long$condition <- factor(summary_cd8_long$condition, levels = c("unstim", "aPD1", "aIFNyR1+aPD1", "hrIFNy", "hrIFNy_high"))
summary_cd8_long <- summary_cd8_long[summary_cd8_long$condition != "hrIFNy_high",] #remove hrIFNy_high fragments

summary_cd8_long$segment <- factor(summary_cd8_long$segment, levels = c("TLS", "intermediate", "tumour_bed"))

ggplot(summary_cd8_long, aes(x=segment, y = value, fill = variable)) + geom_col() + facet_grid(~condition) + theme_minimal() +
  scale_fill_manual(values = c("darkgoldenrod1", "darkred", "pink","darkcyan","chartreuse4","cornflowerblue","purple")) #plot the composition of CD8+ cells


#repeat for CD4+ populations
cd4 <- fragments_small[,c("Name","experiment","tumour", "condition", "fragment","segment","CD4+_percentage","CD4+ CD25+_percentage","CD4+ CD39+_percentage","CD4+ CD103+_percentage","CD4+ CD137+_percentage","CD4+ OX40+_percentage","CD4+ PD-1+_percentage","CD4+ IL7R+_percentage")]
summary_cd4 <- cd4 %>%
  group_by(condition, segment) %>%
  summarize(across(6:12, \(x) mean(x, na.rm = TRUE)))

colnames(summary_cd4) <- gsub("_percentage", "", colnames(summary_cd4))

summary_cd4_long <- melt(summary_cd4)

summary_cd4_long$condition <- factor(summary_cd4_long$condition, levels = c("unstim", "aPD1", "aIFNyR1+aPD1", "hrIFNy", "hrIFNy_high"))
summary_cd4_long <- summary_cd4_long[summary_cd4_long$condition != "hrIFNy_high",]

summary_cd4_long$segment <- factor(summary_cd4_long$segment, levels = c("TLS", "intermediate", "tumour_bed"))

ggplot(summary_cd4_long, aes(x=segment, y = value, fill = variable)) + geom_col() + facet_grid(~condition) + theme_minimal() +
  scale_fill_manual(values = c("darkgoldenrod1", "darkred", "pink","darkcyan","chartreuse4","cornflowerblue","purple"))
```

```{r Calculate correlations}
#Calculate correlations between different parameters
fragment_noPD1 <- fragments_small[fragments_small$condition %in% c("unstim", "hrIFNy"),] #for correlations inolving PD-1+ cells, exclude conditions where aPD1 is added (as it cannot be measured there)

#first test aPD1, which can only be done in conditions where it is not blocked
cor_coefs <- cor.test(fragment_noPD1$B_cell_percentage, fragment_noPD1$`CD8+ PD-1+_percentage`) #calculate the correlation coefficient
ggplot(fragment_noPD1, aes(x= B_cell_percentage, y = `CD8+ PD-1+_percentage`)) + geom_point() + geom_smooth(method='lm', formula= y~x) +
  annotate("text", x = 0, y = 112, label = paste0("R: ", round(cor_coefs$estimate, 2))) +
  annotate("text", x = 15, y = 112, label = paste0("p-value: ", round(cor_coefs$p.value, 10))) #plot a correlation curve

cor_coefs <- cor.test(fragment_noPD1$B_cell_percentage, fragment_noPD1$`CD4+ PD-1+_percentage`) #calculate the correlation coefficient
ggplot(fragment_noPD1, aes(x= B_cell_percentage, y = `CD4+ PD-1+_percentage`)) + geom_point() + geom_smooth(method='lm', formula= y~x) +
  annotate("text", x = 0, y = 112, label = paste0("R: ", round(cor_coefs$estimate, 2))) +
  annotate("text", x = 15, y = 112, label = paste0("p-value: ", round(cor_coefs$p.value, 10))) #plot a correlation curve

#make a function to plot other correlations
plot_correlation <- function(x, y){
  column_x <- fragments_small[,colnames(fragments_small) == x] #select the x column based on the provided column name
  column_y <- fragments_small[,colnames(fragments_small) == y] #select the y column based on the provided column name
  
  cor_coefs <- cor.test(x = column_x, y = column_y) #calculate the correlation coefficient between column x and y
  ggplot(fragments_small, aes(x=column_x, y = column_y)) + geom_point() + geom_smooth(method='lm', formula= y~x) + xlab(x) + ylab(y) +
    annotate("text", x = 0, y = 112, label = paste0("R: ", round(cor_coefs$estimate, 2))) +
    annotate("text", x = 15, y = 112, label = paste0("p-value: ", round(cor_coefs$p.value, 10))) #plot the correlation
}

#plot several correlations using the specified function
plot_correlation("B_cell_percentage", "CD8+ CD39+ CD137+_percentage")
plot_correlation("B_cell_percentage", "CD4+ IL7R+_percentage")
plot_correlation("B_cell_percentage", "CD8+ IL7R+_percentage")
plot_correlation("B_cell_percentage", "CD8+ CD25+_percentage")

plot_correlation("B_cell_percentage", "CD4+_percentage")
plot_correlation("B_cell_percentage", "CD8+_percentage")

#plot the correlation between CD4 and CD8 percentage (of CD45) and the B cell percentage
cd4 <- fragments_small[,c("Name", "B_cell_percentage", "CD3+_percentage", "CD4+_percentage", "CD8+_percentage")]
cd4$`CD4+_of_CD45` <- (cd4$`CD3+_percentage`/100) * (cd4$`CD4+_percentage`/100) *100 #the CD4+ population is given as a % of CD3+; to get to CD45+, multiply this number with the percentage CD3+ of CD45+
cd4$`CD8+_of_CD45` <- (cd4$`CD3+_percentage`/100) * (cd4$`CD8+_percentage`/100) *100 #same for CD8+

#calculate the ratio of CD4/CD8; both using the percentage of CD3+ and the percentage of CD45+
cd4$cd4_cd8_ratio <- cd4$`CD4+_percentage`/cd4$`CD8+_percentage`
cd4$cd4_cd8_ratio_cd45 <- cd4$`CD4+_of_CD45`/cd4$`CD8+_of_CD45`


write.csv(cd4, "~/Documents/Analyses/TLS/mass_data_export/CD4_of_CD45.csv") #export as csv

#plot several correlations using CD4+ and CD8+ percentages
cor_coefs <- cor.test(x = cd4$B_cell_percentage, y = cd4$`CD4+_of_CD45`)
ggplot(cd4, aes(x=B_cell_percentage, y = `CD4+_of_CD45`)) + geom_point() + geom_smooth(method='lm', formula= y~x) + xlab("B cell percentage") + ylab("CD4+ (%of CD45+)") +
  annotate("text", x = 0, y = 112, label = paste0("R: ", round(cor_coefs$estimate, 2))) +
  annotate("text", x = 15, y = 112, label = paste0("p-value: ", round(cor_coefs$p.value, 10)))

cor_coefs <- cor.test(x = cd4$B_cell_percentage, y = cd4$`CD8+_of_CD45`)
ggplot(cd4, aes(x=B_cell_percentage, y = `CD8+_of_CD45`)) + geom_point() + geom_smooth(method='lm', formula= y~x) + xlab("B cell percentage") + ylab("CD8+ (%of CD45+)") +
  annotate("text", x = 0, y = 112, label = paste0("R: ", round(cor_coefs$estimate, 2))) +
  annotate("text", x = 15, y = 112, label = paste0("p-value: ", round(cor_coefs$p.value, 10)))

cor_coefs <- cor.test(x = cd4$B_cell_percentage, y = cd4$cd4_cd8_ratio)
ggplot(cd4, aes(x=B_cell_percentage, y = cd4_cd8_ratio)) + geom_point() + geom_smooth(method='lm', formula= y~x) + xlab("B cell percentage") + ylab("Rato of CD4+/CD8+") +
  annotate("text", x = 0, y = 112, label = paste0("R: ", round(cor_coefs$estimate, 2))) +
  annotate("text", x = 15, y = 112, label = paste0("p-value: ", round(cor_coefs$p.value, 10)))

cor_coefs <- cor.test(x = cd4$B_cell_percentage, y = cd4$cd4_cd8_ratio_cd45)
ggplot(cd4, aes(x=B_cell_percentage, y = cd4_cd8_ratio_cd45)) + geom_point() + geom_smooth(method='lm', formula= y~x) + xlab("B cell percentage") + ylab("Rato of CD4+/CD8+") +
  annotate("text", x = 0, y = 112, label = paste0("R: ", round(cor_coefs$estimate, 2))) +
  annotate("text", x = 15, y = 112, label = paste0("p-value: ", round(cor_coefs$p.value, 10)))
```

```{r Investigate cell numbers in TLS, tumour and intermediate}
#calculate whether TLS segments have more cells than other segments
aov_cd45 <- aov(percent_of_CD45 ~ segment, data = fragments_small) #perform an ANOVA to investigate the relation between the cell count (as % of CD45+ total form the tSNE) and the fragment type
summary(aov_cd45)
TukeyHSD(aov_cd45) #perform multiple comparisons between fragment types using Tukey's test

#export the cell counts to Prism
cd45_small <- fragments_small[,c("Name", "percent_of_CD45", "segment")]
colnames(cd45_small) <- c("Name", "value", "segment")
cd45_small$segment <- factor(cd45_small$segment, levels = c("TLS", "intermediate", "tumour_bed"))
cd45_wide <- reshape(cd45_small, idvar = "Name", timevar = "segment", direction = "wide")
colnames(cd45_wide) <- c("name", "tumour bed", "intermediate", "TLS")

write.csv(cd45_wide, "~/Documents/Analyses/TLS/mass_data_export/CD45_percentage_segment.csv") #export as csv

ggplot(cd45_small, aes(x=segment, y = value)) + geom_boxplot() +geom_jitter() #also plot the result in R
```
